/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai.rbs;

import ai.rbs.inference.InferenceEngine;
import ai.rbs.inference.RETENetwork;
import ai.rbs.knowledge.KnowledgeBase;
import ai.rbs.knowledge.Rule;
import sun.misc.FDBigInteger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Miguel
 */
public class UI extends javax.swing.JFrame {
    int banderaEliminar =0;
    String [] ruleid;
    int ruleidTable3;

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Antecedentes ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Consecuentes");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Reglas ");

        jButton1.setText("Eliminar");

        jButton2.setText("Actualizar");

        jButton3.setText("Insertar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                   },
                new String [] {
                        "Rules"
                }
        ));

        KnowledgeBase kb  = new KnowledgeBase();

        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();


        for (Rule r : kb.getRules()) {
            String Antecedentes="";

            int tamaño=r.getAntecedents().size();
            int cont=0;
            for ( String l: r.getAntecedents() ) {
                cont++;
                if (cont==tamaño)
                {
                    Antecedentes=Antecedentes+l;

                }else
                    Antecedentes=Antecedentes+l+",";
            }

            String regla=Antecedentes+"-"+r.getConsequent();
           // String [] rule = regla;
            modelo.addRow(new Object[]{r.getId()+" "+regla});

        }



        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton2)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jButton3)))
                                                .addGap(25, 25, 25))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2)
                                                        .addComponent(jButton3)))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Base de Conocimietos ", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton4.setText("Definir Hechos");

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton5.setText("Encadenamiento Hacia Adelante ");

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton6.setText("Encadenamiento hacia Atras ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Hechos Iniciales");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "Ciclo", "Base de Hechos", "Conjunto Conflicto", "Resoluciòn", "Meta Actual"
                }
        ));
        jScrollPane1.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Resultados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(385, 385, 385)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jButton5)
                                                                .addGap(57, 57, 57)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jButton4)
                                                                                .addGap(54, 54, 54)
                                                                                .addComponent(jButton6)))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );



        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5)
                                        .addComponent(jButton6))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Base de Hechos ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Reglas Eliminadas");

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton7.setText("Recuperar");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                   },
                new String [] {
                        "Reglas"
                }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                                .addGap(81, 81, 81)
                                .addComponent(jButton7)
                                .addGap(55, 55, 55))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(85, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(216, 216, 216)
                                                .addComponent(jButton7))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Reglas eliminadas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();



        DefaultTableModel modelo3= (DefaultTableModel) jTable3.getModel();
        modelo3.setRowCount(0);
        for (Rule r : kb.getDeletedRules()) {
            String Antecedentes="";

            int tamaño=r.getAntecedents().size();
            int cont=0;
            for ( String l: r.getAntecedents() ) {
                cont++;
                if (cont==tamaño)
                {
                    Antecedentes=Antecedentes+l;

                }else
                    Antecedentes=Antecedentes+l+",";
            }

            String regla=Antecedentes+"-"+r.getConsequent();
            // String [] rule = regla;
            modelo3.addRow(new Object[]{r.getId()+" "+regla});

        }






        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = jTable1.columnAtPoint(evt.getPoint());

                if (row == -1){
                    JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                } else {
                                      String [] rule =modelo.getValueAt(row,0).toString().split("-");

                    jTextField1.setText(rule[0]);
                    jTextField2.setText(rule[1]);
                    ruleid=rule[0].split(" ");
                    //JOptionPane.showMessageDialog(null, " ha seleccionado la regla del id "+ruleid[0]);

                }


            }
        });

        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable3.rowAtPoint(evt.getPoint());
                int col = jTable3.columnAtPoint(evt.getPoint());

                if (row == -1){
                    JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                } else {
                    String [] rule =modelo3.getValueAt(row,0).toString().split(" ");

                    ruleidTable3=Integer.parseInt(rule[0]);
                    //JOptionPane.showMessageDialog(null, " ha seleccionado la regla del id "+ruleidTable3);

                }


            }
        });
        jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int filaseleccionada;
                try{
                    //Guardamos en un entero la fila seleccionada.
                    filaseleccionada = jTable1.getSelectedRow();
                    if (filaseleccionada == -1){
                        JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                    } else {

                        kb.modifyRuleStatus(Integer.parseInt(ruleid[0]));
                        jTextField1.setText("");
                        jTextField2.setText("");
                        llenadoReglas();
//                        JOptionPane.showMessageDialog(null, " ha seleccionado la regla del id "+ruleid[0]);

                    }
                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }


            }
        });



        jButton2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {


                int filaseleccionada;
                try{
                    //Guardamos en un entero la fila seleccionada.
                    filaseleccionada = jTable1.getSelectedRow();
                    if (filaseleccionada == -1){
                        JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                    } else {

                        String [] antecedente = jTextField1.getText().split(" ");
                        String [] auxAntecedentes=antecedente[1].split(",");

                        List<String> antecedents = new ArrayList<>();
                        for (String s: auxAntecedentes) {
                            antecedents.add(s);
                        }

                        kb.modifyRule(new Rule(Integer.parseInt(ruleid[0]),jTextField2.getText(),antecedents));
                        JOptionPane.showMessageDialog(null,"Se actualizo la regla "+ ruleid[0]);
                        jTextField1.setText("");
                        jTextField2.setText("");
                        antecedents.clear();
                        llenadoReglas();
//                      JOptionPane.showMessageDialog(null, " ha seleccionado la regla del id "+ruleid[0]);

                    }
                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }
            }
        });



        jButton3.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                int filaseleccionada;
                try{
                    //Guardamos en un entero la fila seleccionada.
                    filaseleccionada = jTable1.getSelectedRow();

                        String [] antecedente = jTextField1.getText().split(",");

                        List<String> antecedents = new ArrayList<>();
                        for (String s: antecedente) {
                            antecedents.add(s);
                        }
                        //JOptionPane.showMessageDialog(null," "+0+" "+jTextField2.getText()+" "+antecedents);

                        kb.insertRule(new Rule(0,jTextField2.getText(),antecedents));

                        antecedents.clear();
                        llenadoReglas();
                        JOptionPane.showMessageDialog(null, "Regla insertada");
                        jTextField1.setText("");
                        jTextField2.setText("");

                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        FactBase FB = new FactBase();

        jButton4.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    //Guardamos en un entero la fila seleccionada.
                    String [] hecho = jTextField3.getText().split(",");


                    List<String> hechos = new ArrayList<>();
                    for (String s: hecho) {
                        hechos.add(s);
                    }
                    //JOptionPane.showMessageDialog(null," "+0+" "+jTextField2.getText()+" "+hechos);
                    JOptionPane.showMessageDialog(null,"Hechos definidos");
                    jTextField3.setText("");
                    FB.setFacts(hechos);
                    //hechos.clear();

                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        jButton5.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    DefaultTableModel modelo2= (DefaultTableModel) jTable2.getModel();
                    modelo2.setRowCount(0);
                    InferenceEngine IE = new InferenceEngine();
                    RETENetwork RN = new RETENetwork();
                    kb.setGoalsFacts();
                    RN.create(kb.getRules());
                    JustificationModule JM = new JustificationModule();

                    if( IE.forwardChaining(FB.getFacts(),kb,RN,JM))
                    {
                        JOptionPane.showMessageDialog(null,"el sujeto esta consumiendo "+FB.getFacts().get(FB.getFacts().size()-1));
                        for (String [] s: JM.getJustification()
                             ) {
                            modelo2.addRow(new Object[]{s[0],s[1],s[2],s[3],s[4]});
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"No hay suficientes datos para completar el encadenamiento");
                    }
                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }
            }
        });


        jButton7.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                int filaseleccionada;
                try{
                    //Guardamos en un entero la fila seleccionada.
                    filaseleccionada = jTable3.getSelectedRow();
                    if (filaseleccionada == -1){
                        JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                    } else {

                        kb.modifyRuleStatus(ruleidTable3);
                        llenadoReglas();
//                        JOptionPane.showMessageDialog(null, " ha seleccionado la regla del id "+ruleid[0]);
                    }
                }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }
            }
        });


    }// </editor-fold>//GEN-END:initComponents


    public void llenadoReglas()
    {
        KnowledgeBase kb  = new KnowledgeBase();

        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (Rule r : kb.getRules()) {
            String Antecedentes="";

            int tamaño=r.getAntecedents().size();
            int cont=0;
            for ( String l: r.getAntecedents() ) {
                cont++;
                if (cont==tamaño)
                {
                    Antecedentes=Antecedentes+l;

                }else
                    Antecedentes=Antecedentes+l+",";
            }

            String regla=Antecedentes+"-"+r.getConsequent();
            // String [] rule = regla;
            modelo.addRow(new Object[]{r.getId()+" "+regla});
        }


        DefaultTableModel modelo3= (DefaultTableModel) jTable3.getModel();
        modelo3.setRowCount(0);

        for (Rule r : kb.getDeletedRules()) {
            String Antecedentes="";

            int tamaño=r.getAntecedents().size();
            int cont=0;
            for ( String l: r.getAntecedents() ) {
                cont++;
                if (cont==tamaño)
                {
                    Antecedentes=Antecedentes+l;

                }else
                    Antecedentes=Antecedentes+l+",";
            }

            String regla=Antecedentes+"-"+r.getConsequent();
            // String [] rule = regla;
            modelo3.addRow(new Object[]{r.getId()+" "+regla});
        }
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    public  void createUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}